// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com.takuyamashita/ecs-demo-next-echo/src/echo/demo/ent/runtime.go

const (
	Version = "v0.13.1"                                         // Version of ent codegen.
	Sum     = "h1:uD8QwN1h6SNphdCCzmkMN3feSUzNnVvV/WIkHKMbzOE=" // Sum of ent codegen.
)
