version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:949545720247:task-definition/next:30"
        LoadBalancerInfo:
          ContainerName: "next"
          ContainerPort: 3000