name: Deploy Next.js

on:
  push:
    branches:
      - main
    paths:
      #- 'ignore'

permissions:
  id-token: write
  contents: read

env:
  ECR_REPOSITORY: next
  ECS_SERVICE: next
  ECS_CLUSTER: next
  ECS_TASK_DEFINITION: environment/aws/ecs_next_task_definition.json
  CODEDEPLOY_APPSPEC: environment/aws/code_deploy_next_appspec.yml
  CONTAINER_NAME: next

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for China region audience
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }} 
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      
      - name: Get the Amazon Repository URI
        id: get-repository-uri
        run: |
          echo "::set-output name=repository_uri::$(aws ssm get-parameter --name /next/ecr --query 'Parameter.Value' --output text)"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -f ./environment/docker/next/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      
      - name: environment value from ssm parameter store
        id: get-ssm-parameter
        run: |
          echo "API_ENDPOINT=$(aws ssm get-parameter --name /echo/api_endpoint --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
          echo "LOG_GROUP_NAME=$(aws ssm get-parameter --name /next/log_group_name --query 'Parameter.Value' --output text)" >> $GITHUB_ENV

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}
          environment-variables: |
            API_ENDPOINT=${{ steps.get-ssm-parameter.outputs.API_ENDPOINT }}
          log-configuration-options: |
            awslogs-group=${{ steps.get-ssm-parameter.outputs.LOG_GROUP_NAME }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}

          codedeploy-appspec: ${{ env.CODEDEPLOY_APPSPEC }}
          codedeploy-application: next
          codedeploy-deployment-group: next 

          wait-for-service-stability: true
